### ISSUE TITLE
Ensuring Versioned and Module-Specific S3 Bucket Structure for Terraform State Management

### ISSUE THREAD

**Issue by leiicamundi** [camunda/camunda-deployment-references#133]
Following https://github.com/camunda/camunda-deployment-references/pull/128, we need to ensure that each cluster’s S3 bucket path includes:  
1. The **module path** (using `S3_BACKEND_BUCKET_PREFIX`)  
2. The **Camunda version** (to isolate Terraform states across versions)  

### **Required Configuration**  
Each module must set `S3_BACKEND_BUCKET_PREFIX` to its corresponding path in the S3 bucket.  

**Example for the ROSA dual-region module:**  
```yaml
S3_BACKEND_BUCKET_PREFIX: aws/openshift/rosa-hcp-dual-region/ # Must match the module path
```

By appending the Camunda version dynamically, Terraform states will be stored in:  
```
s3://my-terraform-bucket/aws/openshift/rosa-hcp-dual-region/8.5.0/
```

This ensures that each module has a dedicated location and avoids conflicts between versions.  

---

#### **1. Cluster Creation and Deletion Must Use the Correct Paths**  
All workflows and actions handling cluster creation and deletion **must incorporate `S3_BACKEND_BUCKET_PREFIX` and `CAMUNDA_VERSION`**.  

#### **2. Cluster Deletion**  
Terraform cleanup actions must delete the correct versioned state.  
```yaml
- name: Delete clusters
  id: delete_clusters
  timeout-minutes: 125
  uses: ./.github/actions/aws-openshift-rosa-hcp-dual-region-cleanup
  env:
      RHCS_TOKEN: ${{ steps.secrets.outputs.RH_OPENSHIFT_TOKEN }}
  with:
      tf-bucket-key-prefix: ${{ env.S3_BACKEND_BUCKET_PREFIX }}${{ steps.camunda-version.outputs.CAMUNDA_VERSION }}/
```

#### **3. Cluster Creation**  
When provisioning a cluster, Terraform must store its state in the correct versioned path.  
```yaml
- name: Create ROSA cluster and login
  uses: ./.github/actions/aws-openshift-rosa-hcp-dual-region-create
  id: create_clusters
  if: always() && success()
  with:
      s3-bucket-key-prefix: ${{ env.S3_BACKEND_BUCKET_PREFIX }}${{ steps.camunda-version.outputs.CAMUNDA_VERSION }}/
```

---

### **Verifying the Bucket Structure**  
To confirm that the state files are stored correctly, run:  
```bash
aws s3 ls "s3://$BUCKET/$KEY_PREFIX"
```
For example:  
```bash
BUCKET=my-terraform-bucket
KEY_PREFIX=aws/openshift/rosa-hcp-dual-region/8.5.0/
aws s3 ls "s3://$BUCKET/$KEY_PREFIX"
```
Expected output:  
```
2024-03-19 12:30:45      1024 terraform.tfstate
2024-03-19 12:30:46      2048 terraform.tfstate.backup
```

---

### **Key Takeaways**  
- [ ] **Each module must define `S3_BACKEND_BUCKET_PREFIX` to match its path.**  
- [ ] **All workflows and actions (creation, deletion, Terraform operations) must use the correct versioned bucket path.**  
- [ ] **Terraform state files will be stored in versioned directories, preventing conflicts.**
